#!/usr/bin/env php
<?php
   require_once("init.php");

   $db=app()->getDb();

   #db query

   echo "> check db config\n";
   try{
      $rows=$db->fetchAll("show tables");
   }
   catch(Exception $e)
   {
      echo "db not config\n";
      exit(1);
   }

   $dbs=app()->getSetting("dbs");
   $db_setting=$dbs['default'];

   $host= $db_setting['host'];
   $username= $db_setting['username'];
   $password= $db_setting['password'];
   $dbname= $db_setting['dbname'];

   if($password)
   {
      $cmd=sprintf("mysql -h %s -u %s -P%s %s %s < data/db.sql",$host,$username,$password,$dbname);
   }
   else
   {
      $cmd=sprintf("mysql -h %s -u %s %s %s < data/db.sql",$host,$username,$password,$dbname);
   }


   //echo $cmd;
   echo "> init db\n";
   execute_cmd("mysql -u root test < data/db.sql");

   echo "> finished \n";
   /*
   assert(count($rows) > 0);

   $select=$db->select();
   $select->from("blog");
   $rows=$db->fetchAll($select);
   assert(count($rows) > 0);

   */

