<form method="post">
   <input name="id" type="hidden" value="<?php echo $this->data['id']; ?>" />


   <table class="table table-bordered">
      <tr>
         <td>Title</td>
         <td><input name="title" type="text" value="<?php echo $this->data['title']; ?>" /></td>
      </tr>
      <tr>
         <td>Content</td>
         <td><textarea name="content"><?php echo $this->data['content'];?></textarea></td>
      </tr>
      <tr>
         <td></td>
         <td><input type="submit" value="Submit"/></td>
      </tr>
   </table>
</form>
